Feat update memkind integration step3
pmem/redis pull request #102
Opened 2019-03-15 08:26 UTC by michalbiesek

This PR contains changes to remove unecessary dependency memkind_malloc "proxy":
Please review this changes after mergin #99,#100 and #101

2019-03-20 06:58 UTC, michalbiesek commented
@KFilipek 
Kindly ping, I rebase it.

2019-03-20 19:56 UTC, KFilipek requested changes
> Reviewed 7 of 8 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/102)* status: all files reviewed, 10 unresolved discussions (waiting on @michalbiesek)

___
*[src/zmalloc.c, line 92 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaReRn06J_0WCDMkyXK:-LaReRn06J_0WCDMkyXL:b-k1rv3i) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L92)):*
> ```C
> static struct memkind *pmem_kind;
> 
> void zmalloc_init_pmem(const char* pm_dir_path, size_t pm_file_size)
> ```

Typically Redis leave bracket after function header:
void zmalloc_init_pmem(const char* pm_dir_path, size_t pm_file_size) {
___
*[src/zmalloc.c, line 93 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRedl98XDOAMyQt2N1:-LaRedl98XDOAMyQt2N2:b-dce0cp) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L93)):*
> ```C
> 
> void zmalloc_init_pmem(const char* pm_dir_path, size_t pm_file_size)
> ```

Unnecessary space
___
*[src/zmalloc.c, line 103 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRehE3-VnhQ9WViOT-:-LaRehE3-VnhQ9WViOT0:b-jortj9) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L103)):*
> ```C
>     }
> }
> void zmalloc_destroy_pmem()
> ```

missing bracket in the same line
___
*[src/zmalloc.c, line 134 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaReks475IFwl0UIcjm:-LaReks475IFwl0UIcjn:brzqond) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L134)):*
> ```C
> void *zmalloc_pmem(size_t size) {
> #ifdef USE_MEMKIND
>     void* ptr = memkind_malloc(pmem_kind,size + MEMKIND_PREFIX_SIZE);
> ```

missing space before size
___
*[src/zmalloc.c, line 134 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRenpB8bv7fMh1PlQE:-LaRenpB8bv7fMh1PlQF:b-blba8g) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L134)):*
> ```C
> void *zmalloc_pmem(size_t size) {
> #ifdef USE_MEMKIND
>     void* ptr = memkind_malloc(pmem_kind,size + MEMKIND_PREFIX_SIZE);
> ```

asterisk should be moved to variable name
___
*[src/zmalloc.c, line 235 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRewueAQYFt3KAsvsr:-LaRewuf7oLkSGzXXIIE:b-wjxh2c) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L235)):*
> ```C
>             *is_ram = 1;
>             return (char*)new_ptr + MEMKIND_PREFIX_SIZE;
>         }
> ```

} else {
___
*[src/zmalloc.c, line 237 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaReuAlDdqPv1m58CQ0:-LaReuAlDdqPv1m58CQ1:b5e3e9n) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L237)):*
> ```C
>         }
>         else {
>             new_ptr = memkind_realloc(pmem_kind,(void*)(is_ram), size + MEMKIND_PREFIX_SIZE);
> ```

missing space before casting
___
*[src/zmalloc.c, line 294 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRf2fl8ODmAc9olQ8s:-LaRf2fl8ODmAc9olQ8t:b-6fac61) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L294)):*
> ```C
>     {
>         uint64_t *is_ram = (uint64_t*)((char*)(ptr) - MEMKIND_PREFIX_SIZE);
>         if(*is_ram) {
> ```

missing space
___
*[src/zmalloc.c, line 296 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRf1aW5HGCHq-ZsMnB:-LaRf1aW5HGCHq-ZsMnC:b-6fac61) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L296)):*
> ```C
>         if(*is_ram) {
>             zfree_local(is_ram);
>         }else {
> ```

missing space
___
*[src/zmalloc.c, line 297 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRf-ex1zz-zFgFbpw1:-LaRf-ex1zz-zFgFbpw2:b-mlkqre) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L297)):*
> ```C
>             zfree_local(is_ram);
>         }else {
>             memkind_free(pmem_kind,  is_ram);
> ```

2 spaces instead of 1


<!-- Sent from Reviewable.io -->

2019-03-21 07:12 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/102)* status: 6 of 8 files reviewed, 10 unresolved discussions (waiting on @KFilipek)

___
*[src/zmalloc.c, line 92 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaReRn06J_0WCDMkyXK:-LaU0paU4dZ8roGt-pe_:b-896fix) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L92)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Typically Redis leave bracket after function header:
void zmalloc_init_pmem(const char* pm_dir_path, size_t pm_file_size) {
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 93 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRedl98XDOAMyQt2N1:-LaU46jn9wPdVPH4nxrY:bc4a7q7) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L93)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Unnecessary space
</blockquote></details>

? mark the place please
___
*[src/zmalloc.c, line 103 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRehE3-VnhQ9WViOT-:-LaU4-eV-PNeQCqqL8-T:b-896fix) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L103)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

missing bracket in the same line
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 134 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaReks475IFwl0UIcjm:-LaU4MdJ6zXFbqAaoslM:b-896fix) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L134)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

missing space before size
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 134 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRenpB8bv7fMh1PlQE:-LaU4RxuDRchWKlnK7Df:b-896fix) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L134)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

asterisk should be moved to variable name
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 235 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRewueAQYFt3KAsvsr:-LaU4d093LGHtXQtSODK:b-896fix) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L235)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

} else {
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 237 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaReuAlDdqPv1m58CQ0:-LaU4kk1AccY9TCIFmtc:b-896fix) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L237)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

missing space before casting
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 294 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRf2fl8ODmAc9olQ8s:-LaU4qZg6qigDv_kdCQz:b-896fix) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L294)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 296 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRf1aW5HGCHq-ZsMnB:-LaU4qw56QEhupQhlMQ6:b-896fix) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L296)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

missing space
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 297 at r2](https://reviewable.io/reviews/pmem/redis/102#-LaRf-ex1zz-zFgFbpw1:-LaU4wci-MbKdiXht3En:b-896fix) ([raw file](https://github.com/pmem/redis/blob/f8b5a201a71fa6887e2eb93cff0912b591b07ea1/src/zmalloc.c#L297)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

2 spaces instead of 1
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2019-03-21 09:07 UTC, jschmieg approved these changes

2019-03-21 09:07 UTC, merged