Dynamic ratio in idle
pmem/redis pull request #158
Opened 2020-03-26 13:30 UTC by jschmieg

Modifying the internal threshold when there is no incoming traffic may result in an increasing threshold indefinitely.

2020-03-27 14:43 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/158)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @jschmieg)

___
*[src/pmem.c, line 68 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3RQ_bp5RpCiSFzgxDf:-M3RQ_br26nJi12B3fjX:b4e68j6) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L68)):*
> ```
> (long long)fabs((signed long long)total_memory_checkpoint-(signed long long)total_memory)
> ```
nit: we could use macro/inline function to find the diff value between unsigned values
#define ABS_DIFF(a,b) a > b ? a - b : b -a;
and avoid this casting


<!-- Sent from Reviewable.io -->

2020-03-27 20:23 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/158)* status: 0 of 3 files reviewed, 3 unresolved discussions (waiting on @jschmieg)

___
*[src/pmem.c, line 85 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3SbzMYCe3Bt5x8F6YA:-M3SbzMYCe3Bt5x8F6YB:b-clarep) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L85)):*
> ```
>             server.pmem_checkpoint_value = pmem_memory;
>             server.dram_checkpoint_value = dram_memory;
> ```
I know this is still in development, but consider saving the value from two parameter as one - you are only interested of sum.
___
*[src/server.h, line 1329 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3SdgFP1cHWqIorWawj:-M3SdgFP1cHWqIorWawk:boazusm) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/server.h#L1329)):*
> ```
>     size_t pmem_checkpoint_value;             /* PMEM utylization in last checkpoint*/
>     size_t dram_checkpoint_value;             /* DRAM utylization in last checkpoint*/
> ```
nit: I am not sure but I think this information would fit better in stats section - somewhere here https://github.com/pmem/redis/blob/fc6c7cec251abe6a72f8ee50705d43a257403f2d/src/server.h#L1106


<!-- Sent from Reviewable.io -->

2020-03-28 15:47 UTC, KFilipek requested changes
> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/158)* status: all files reviewed, 6 unresolved discussions (waiting on @jschmieg)

___
*[src/pmem.c, line 68 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3WmYtuEumVa40jZ-zr:-M3WmYtuEumVa40jZ-zs:byfu64w) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L68)):*
> ```
> (signed long long)total_memory_checkpoint-(signed long long)total_memory
> ```
fabs takes double as an argument.
What's the problem with following line, AFAIK: double > 100 works fine:
if (fabs(args) > 100)
___
*[src/pmem.c, line 70 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3WnUQG2F-KcpSvb97R:-M3WnUQG2F-KcpSvb97S:bairxmz) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L70)):*
> ```C
>             if( (long long)fabs((signed long long)total_memory_checkpoint-(signed long long)total_memory) > 100) {
>                 //revert logic to avoid division by zero
>                 float setting_state = (float)server.dram_pmem_ratio.pmem_val/server.dram_pmem_ratio.dram_val;
> ```

Lost precision.
Use double, then pass it without casting to fabs in the next line.
___
*[src/server.h, line 1329 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3WjNTRDnKTG7Rx8ErT:-M3WjNTS-wClT-vz2QWy:bvy05a9) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/server.h#L1329)):*
> ```objc
>     unsigned int dynamic_threshold_max;       /* Maximum value of dynamic threshold */
>     ratioDramPmemConfig dram_pmem_ratio;      /* DRAM/Persistent Memory ratio */
>     size_t pmem_checkpoint_value;             /* PMEM utylization in last checkpoint*/
> ```

utylization -> utilization (x2)


<!-- Sent from Reviewable.io -->

2020-03-30 10:32 UTC, jschmieg commented
___
*[src/pmem.c, line 68 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3WmYtuEumVa40jZ-zr:-M3ezT8G0cHstdBnwdZ3:b-kcyfey) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L68)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

> ```
> (signed long long)total_memory_checkpoint-(signed long long)total_memory
> ```
fabs takes double as an argument.
What's the problem with following line, AFAIK: double > 100 works fine:
if (fabs(args) > 100)
</blockquote></details>

Without checking which size_t (unsigned) is bigger, the result may be negative and give overflow when subtracting. 
Casting result to signed or using ABS_DIFF will help here.


<!-- Sent from Reviewable.io -->

2020-03-31 08:49 UTC, KFilipek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/158)* status: all files reviewed, 6 unresolved discussions (waiting on @jschmieg)

___
*[src/pmem.c, line 68 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3WmYtuEumVa40jZ-zr:-M3jl-9sEG_Pl0KdipQE:b-hk1h17) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L68)):*
<details><summary><i>Previously, jschmieg wrote…</i></summary><blockquote>

Without checking which size_t (unsigned) is bigger, the result may be negative and give overflow when subtracting. 
Casting result to signed or using ABS_DIFF will help here.
</blockquote></details>

The casting of returned value from fabs() is unnecessary


<!-- Sent from Reviewable.io -->

2020-04-02 11:40 UTC, jschmieg reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/158)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @michalbiesek)

___
*[src/pmem.c, line 68 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3RQ_bp5RpCiSFzgxDf:-M3uebgd1eBFn88pzWHR:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L68)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> (long long)fabs((signed long long)total_memory_checkpoint-(signed long long)total_memory)
> ```
nit: we could use macro/inline function to find the diff value between unsigned values
#define ABS_DIFF(a,b) a > b ? a - b : b -a;
and avoid this casting
</blockquote></details>

done
___
*[src/pmem.c, line 68 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3WmYtuEumVa40jZ-zr:-M3uehvcEg-awpaCpV_c:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L68)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

The casting of returned value from fabs() is unnecessary
</blockquote></details>

done
___
*[src/pmem.c, line 70 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3WnUQG2F-KcpSvb97R:-M3ufbsQ2QpaaXnyqSe-:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L70)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Lost precision.
Use double, then pass it without casting to fabs in the next line.
</blockquote></details>

done
___
*[src/pmem.c, line 85 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3SbzMYCe3Bt5x8F6YA:-M3ufdDC6susxuNHmOjO:b16uwrl) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L85)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>             server.pmem_checkpoint_value = pmem_memory;
>             server.dram_checkpoint_value = dram_memory;
> ```
I know this is still in development, but consider saving the value from two parameter as one - you are only interested of sum.
</blockquote></details>

I expect it will be needed soon.
___
*[src/server.h, line 1329 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3SdgFP1cHWqIorWawj:-M3ufhQO6EuTJodota2m:b53trdl) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/server.h#L1329)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
>     size_t pmem_checkpoint_value;             /* PMEM utylization in last checkpoint*/
>     size_t dram_checkpoint_value;             /* DRAM utylization in last checkpoint*/
> ```
nit: I am not sure but I think this information would fit better in stats section - somewhere here https://github.com/pmem/redis/blob/fc6c7cec251abe6a72f8ee50705d43a257403f2d/src/server.h#L1106
</blockquote></details>

I prefer to keep all PMEM related variables in PMEM section.
___
*[src/server.h, line 1329 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3WjNTRDnKTG7Rx8ErT:-M3ugD5vDNMrKwQeaLrp:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/server.h#L1329)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

utylization -> utilization (x2)
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2020-04-02 12:00 UTC, michalbiesek requested changes
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/158)* status: 1 of 5 files reviewed, 4 unresolved discussions (waiting on @jschmieg and @KFilipek)

___
*[src/config.c, line 2217 at r3](https://reviewable.io/reviews/pmem/redis/158#-M3ujMXI3sPZbPyKd6Zb:-M3ujMXI3sPZbPyKd6Zc:buk0sko) ([raw file](https://github.com/pmem/redis/blob/f6c858c3459c876ad3e9aa75ee5355a6612f5a9c/src/config.c#L2217)):*
> ```
> ratio-cron-period
> ```
add at least template in redis.conf
ratio-cron-period name could be more descriptive I mean this only handle the pmem:dram ratio and there are different cron task in redis
___
*[src/pmem.c, line 68 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3RQ_bp5RpCiSFzgxDf:-M3uj1T2DPIlSmdLiMJj:b-bzd7e1) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L68)):*
<details><summary><i>Previously, jschmieg wrote…</i></summary><blockquote>

done
</blockquote></details>


TBH static inline function will be better for that
___
*[src/pmem.c, line 85 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3SbzMYCe3Bt5x8F6YA:-M3ujkI_-2dE2_ZTxumc:b7f15em) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L85)):*
<details><summary><i>Previously, jschmieg wrote…</i></summary><blockquote>

I expect it will be needed soon.
</blockquote></details>

Ok, but please add now  comment with TODO.  If you use in your logic two values than this TODO comment could be easily removed but now you only need sum but for current implementation you only used a sum


<!-- Sent from Reviewable.io -->

2020-04-02 13:09 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/158)* status: 1 of 5 files reviewed, 5 unresolved discussions (waiting on @jschmieg and @KFilipek)

___
*[src/config.c, line 2217 at r3](https://reviewable.io/reviews/pmem/redis/158#-M3uzygk3LUe8d32YbMG:-M3uzygk3LUe8d32YbMH:bx893pf) ([raw file](https://github.com/pmem/redis/blob/f6c858c3459c876ad3e9aa75ee5355a6612f5a9c/src/config.c#L2217)):*
> ```
> 0
> ```
nit: please change it (this is minimum possible value) to positive value:
https://github.com/pmem/redis/blob/fc6c7cec251abe6a72f8ee50705d43a257403f2d/src/server.h#L430
if you have 0 then you have modulo 0 which is Undefined Behavior


<!-- Sent from Reviewable.io -->

2020-04-02 13:23 UTC, jschmieg reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/158)* status: 1 of 6 files reviewed, 4 unresolved discussions (waiting on @KFilipek and @michalbiesek)

___
*[src/config.c, line 2217 at r3](https://reviewable.io/reviews/pmem/redis/158#-M3ujMXI3sPZbPyKd6Zb:-M3v2qfh6umpW6aPump6:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/f6c858c3459c876ad3e9aa75ee5355a6612f5a9c/src/config.c#L2217)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ratio-cron-period
> ```
add at least template in redis.conf
ratio-cron-period name could be more descriptive I mean this only handle the pmem:dram ratio and there are different cron task in redis
</blockquote></details>

done
___
*[src/config.c, line 2217 at r3](https://reviewable.io/reviews/pmem/redis/158#-M3uzygk3LUe8d32YbMG:-M3v2rXoCeUQRAyWHPXU:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/f6c858c3459c876ad3e9aa75ee5355a6612f5a9c/src/config.c#L2217)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> 0
> ```
nit: please change it (this is minimum possible value) to positive value:
https://github.com/pmem/redis/blob/fc6c7cec251abe6a72f8ee50705d43a257403f2d/src/server.h#L430
if you have 0 then you have modulo 0 which is Undefined Behavior
</blockquote></details>

done
___
*[src/pmem.c, line 68 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3RQ_bp5RpCiSFzgxDf:-M3v2t0N-F6lpmXmOurL:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L68)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

TBH static inline function will be better for that
</blockquote></details>

done
___
*[src/pmem.c, line 85 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3SbzMYCe3Bt5x8F6YA:-M3v2uIUCoAv0SEp4NkF:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L85)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Ok, but please add now  comment with TODO.  If you use in your logic two values than this TODO comment could be easily removed but now you only need sum but for current implementation you only used a sum
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2020-04-02 13:31 UTC, michalbiesek requested changes
> Reviewed 1 of 4 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/158)* status: 2 of 6 files reviewed, 6 unresolved discussions (waiting on @jschmieg and @KFilipek)

___
*[src/pmem.c, line 68 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3RQ_bp5RpCiSFzgxDf:-M3v4bfPE_YsXYcdIKhO:b66iwia) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L68)):*
<details><summary><i>Previously, jschmieg wrote…</i></summary><blockquote>

done
</blockquote></details>

nit: space between if and open bracket
___
*[src/pmem.c, line 38 at r4](https://reviewable.io/reviews/pmem/redis/158#-M3v3ufG9AhB42TrJslV:-M3v3ufG9AhB42TrJslW:blmizc5) ([raw file](https://github.com/pmem/redis/blob/fe558861b103b955644e9bf07f21a627d8797dab/src/pmem.c#L38)):*
> ```
> //#define ABS_DIFF(a,b) a > b ? a - b : b -a
> ```
remove
___
*[src/pmem.c, line 41 at r4](https://reviewable.io/reviews/pmem/redis/158#-M3v4-Ww38nh9wdFXXsM:-M3v4-Ww38nh9wdFXXsN:b-c82lqq) ([raw file](https://github.com/pmem/redis/blob/fe558861b103b955644e9bf07f21a627d8797dab/src/pmem.c#L41)):*
> ```
> a - b : b -a
> ```
nit (add space):
a - b : b - a
or even brackets
(a - b) : (b - a)
___
*[tests/unit/introspection.tcl, line 102 at r4](https://reviewable.io/reviews/pmem/redis/158#-M3v4liB5fPy56Tv1es5:-M3v4liB5fPy56Tv1es6:brwagrt) ([raw file](https://github.com/pmem/redis/blob/fe558861b103b955644e9bf07f21a627d8797dab/tests/unit/introspection.tcl#L102)):*
> ```
> ratio-cron-period
> ```
memory-ratio-check-period


<!-- Sent from Reviewable.io -->

2020-04-02 13:43 UTC, jschmieg reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/158)* status: 2 of 6 files reviewed, 5 unresolved discussions (waiting on @KFilipek and @michalbiesek)

___
*[src/pmem.c, line 68 at r2](https://reviewable.io/reviews/pmem/redis/158#-M3RQ_bp5RpCiSFzgxDf:-M3v7WUZ2lG3wrZOINBZ:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/4de7588e82e49a3e5eb88e49a4318c5a8040afaf/src/pmem.c#L68)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

nit: space between if and open bracket
</blockquote></details>

done
___
*[src/pmem.c, line 38 at r4](https://reviewable.io/reviews/pmem/redis/158#-M3v3ufG9AhB42TrJslV:-M3v7UqtAtRHrNPJOtwo:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/fe558861b103b955644e9bf07f21a627d8797dab/src/pmem.c#L38)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> //#define ABS_DIFF(a,b) a > b ? a - b : b -a
> ```
remove
</blockquote></details>

done
___
*[src/pmem.c, line 41 at r4](https://reviewable.io/reviews/pmem/redis/158#-M3v4-Ww38nh9wdFXXsM:-M3v7TdXEoDEy9B7vVid:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/fe558861b103b955644e9bf07f21a627d8797dab/src/pmem.c#L41)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> a - b : b -a
> ```
nit (add space):
a - b : b - a
or even brackets
(a - b) : (b - a)
</blockquote></details>

done
___
*[tests/unit/introspection.tcl, line 102 at r4](https://reviewable.io/reviews/pmem/redis/158#-M3v4liB5fPy56Tv1es5:-M3v7YXk7gEWEx1_fm4o:bb7f2mf) ([raw file](https://github.com/pmem/redis/blob/fe558861b103b955644e9bf07f21a627d8797dab/tests/unit/introspection.tcl#L102)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

> ```
> ratio-cron-period
> ```
memory-ratio-check-period
</blockquote></details>

done


<!-- Sent from Reviewable.io -->

2020-04-02 13:53 UTC, michalbiesek reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/158)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @KFilipek and @michalbiesek)

___
*[src/server.h, line 1331 at r5](https://reviewable.io/reviews/pmem/redis/158#-M3v9YUD8_0n3tXvW5Z6:-M3v9YUE-yVnqG_yydFJ:b-21eivy) ([raw file](https://github.com/pmem/redis/blob/2db93e7ad509d63eeb3f1961c94df4a0fcb7aa40/src/server.h#L1331)):*
> ```
>     size_t dram_checkpoint_value;             /* DRAM utilization in last checkpoint*/
>     int ratio_check_period;                    /* Period of checking ratio in Cron*/
> ```
please fix align the comment


<!-- Sent from Reviewable.io -->

2020-04-02 13:53 UTC, michalbiesek approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/pmem/redis/158#-:-M3v9kgk51p7TLCB_Ks_:bnfp4nl)* status: 2 of 6 files reviewed, 4 unresolved discussions (waiting on @KFilipek and @michalbiesek)



<!-- Sent from Reviewable.io -->

2020-04-02 13:56 UTC, merged