Modifies memcpy and memset functions for PM data
pmem/redis pull request #75
Opened 2018-08-10 09:11 UTC by jschmieg

For PM allocated strings uses pmem_memcpy and pmem_memset from PMDK
library - libpmem. Performance increases for multi-instance scenarios.

2018-08-10 12:40 UTC, michalbiesek commented
___
*[src/memkind_malloc.c, line 76 at r1](https://reviewable.io/reviews/pmem/redis/75#-LJYo4xD3lodahLCN8R8:-LJYo4xE7miamDXPdiYx:bshyeaw) ([raw file](https://github.com/pmem/redis/blob/dbc8201daef420d3273c847e1a13bebce0c64b17/src/memkind_malloc.c#L76)):*
> ```C
> void *pmem_memcpy_wrapper(void *pmemdest, const void *src, size_t len){
>     return pmem_memcpy(pmemdest, src, len ,PMEM_F_MEM_NONTEMPORAL|PMEM_F_MEM_NODRAIN);
> }
> ```

Add empty free line after definition.


<!-- Sent from Reviewable.io -->

2018-08-10 12:40 UTC, michalbiesek commented
___
*[src/memkind_malloc.c, line 79 at r1](https://reviewable.io/reviews/pmem/redis/75#-LJYqXOv28by_n3W7T_S:-LJYqXOv28by_n3W7T_T:b3kqx) ([raw file](https://github.com/pmem/redis/blob/dbc8201daef420d3273c847e1a13bebce0c64b17/src/memkind_malloc.c#L79)):*
> ```C
> void *pmem_memset_wrapper(void *pmemdest, int c, size_t len){
>     return pmem_memset(pmemdest, c, len ,PMEM_F_MEM_NONTEMPORAL|PMEM_F_MEM_NODRAIN);
> }
> ```

.


<!-- Sent from Reviewable.io -->

2018-08-10 12:44 UTC, michalbiesek commented
___
*[src/zmalloc.c, line 216 at r1](https://reviewable.io/reviews/pmem/redis/75#-LJYrMgG5ewMexTaD720:-LJYrMgG5ewMexTaD721:b3kqx) ([raw file](https://github.com/pmem/redis/blob/dbc8201daef420d3273c847e1a13bebce0c64b17/src/zmalloc.c#L216)):*
> ```C
>     atomicGet(used_memory,um);
>     return um;
> }
> ```

.


<!-- Sent from Reviewable.io -->

2018-08-10 12:44 UTC, michalbiesek commented
___
*[src/zmalloc.c, line 219 at r1](https://reviewable.io/reviews/pmem/redis/75#-LJYrOTo9dnzU8S3G1Pq:-LJYrOTo9dnzU8S3G1Pr:b3kqx) ([raw file](https://github.com/pmem/redis/blob/dbc8201daef420d3273c847e1a13bebce0c64b17/src/zmalloc.c#L219)):*
> ```C
> void *zmemcpy(void* dst, const void* src, size_t num){
>     return memcpy(dst, src, num);
> }
> ```

.


<!-- Sent from Reviewable.io -->

2018-08-10 12:44 UTC, michalbiesek reviewed
> Reviewed 8 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/75)* status: all files reviewed, 3 unresolved discussions (waiting on @jschmieg, @karpiop, and @KFilipek)



<!-- Sent from Reviewable.io -->

2018-08-11 08:23 UTC, KFilipek requested changes
> Reviewed 1 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/75)* status: all files reviewed, 5 unresolved discussions (waiting on @jschmieg and @karpiop)

___
*[src/memkind_malloc.c, line 5 at r1](https://reviewable.io/reviews/pmem/redis/75#-LJc48RdCx5Yy0lXSdv_:-LJc48Re7WOak0RdjW4f:bbjel5h) ([raw file](https://github.com/pmem/redis/blob/dbc8201daef420d3273c847e1a13bebce0c64b17/src/memkind_malloc.c#L5)):*
> ```C
> 
> #include <memkind.h>
> #include <libpmem.h>
> ```

Correct header order - alphabetical
___
*[src/memkind_malloc.c, line 75 at r1](https://reviewable.io/reviews/pmem/redis/75#-LJc4CBm1ir1TgUI0oLV:-LJc4CBm1ir1TgUI0oLW:b-4a8u5l) ([raw file](https://github.com/pmem/redis/blob/dbc8201daef420d3273c847e1a13bebce0c64b17/src/memkind_malloc.c#L75)):*
> ```C
> 
> void *pmem_memcpy_wrapper(void *pmemdest, const void *src, size_t len){
>     return pmem_memcpy(pmemdest, src, len ,PMEM_F_MEM_NONTEMPORAL|PMEM_F_MEM_NODRAIN);
> ```

No space in invocation


<!-- Sent from Reviewable.io -->

2018-08-11 08:24 UTC, KFilipek reviewed
> Reviewed 7 of 8 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/75)* status: all files reviewed, 5 unresolved discussions (waiting on @jschmieg and @karpiop)



<!-- Sent from Reviewable.io -->

2018-08-14 09:42 UTC, jschmieg reviewed
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/75)* status: 6 of 8 files reviewed, 5 unresolved discussions (waiting on @KFilipek, @michalbiesek, and @karpiop)

___
*[src/memkind_malloc.c, line 5 at r1](https://reviewable.io/reviews/pmem/redis/75#-LJc48RdCx5Yy0lXSdv_:-LJrn_BQ0HjFUOxMRyw0:bo0sipj) ([raw file](https://github.com/pmem/redis/blob/dbc8201daef420d3273c847e1a13bebce0c64b17/src/memkind_malloc.c#L5)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Correct header order - alphabetical
</blockquote></details>

Done. However I nowhere found that our code follows such rule.
___
*[src/memkind_malloc.c, line 75 at r1](https://reviewable.io/reviews/pmem/redis/75#-LJc4CBm1ir1TgUI0oLV:-LJro12SAIpmBYu8PT7w:b-896fix) ([raw file](https://github.com/pmem/redis/blob/dbc8201daef420d3273c847e1a13bebce0c64b17/src/memkind_malloc.c#L75)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

No space in invocation
</blockquote></details>

Done.
___
*[src/memkind_malloc.c, line 76 at r1](https://reviewable.io/reviews/pmem/redis/75#-LJYo4xD3lodahLCN8R8:-LJro0mWAHqWrXeYX6L4:b-896fix) ([raw file](https://github.com/pmem/redis/blob/dbc8201daef420d3273c847e1a13bebce0c64b17/src/memkind_malloc.c#L76)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

Add empty free line after definition.
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 216 at r1](https://reviewable.io/reviews/pmem/redis/75#-LJYrMgG5ewMexTaD720:-LJroADD0mIABQz7sDua:b-896fix) ([raw file](https://github.com/pmem/redis/blob/dbc8201daef420d3273c847e1a13bebce0c64b17/src/zmalloc.c#L216)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[src/zmalloc.c, line 219 at r1](https://reviewable.io/reviews/pmem/redis/75#-LJYrOTo9dnzU8S3G1Pq:-LJroATgER56vjLSU3hN:b-896fix) ([raw file](https://github.com/pmem/redis/blob/dbc8201daef420d3273c847e1a13bebce0c64b17/src/zmalloc.c#L219)):*
<details><summary><i>Previously, michalbiesek wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2018-08-17 11:32 UTC, karpiop reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/redis/75#-:-LK6e1Zx29f_9WurgRAh:bg7igkv)* status: all files reviewed, 5 unresolved discussions (waiting on @michalbiesek and @KFilipek)



<!-- Sent from Reviewable.io -->

2018-08-27 12:15 UTC, merged